"""column duration in task table added

Revision ID: 111a21b8fa19
Revises: a41a484bfd50
Create Date: 2022-04-14 17:32:02.330727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '111a21b8fa19'
down_revision = 'a41a484bfd50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('duration', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'duration')
    # ### end Alembic commands ###
