"""tasks table creation

Revision ID: 55badc63f5fb
Revises: 7605e7d9f82d
Create Date: 2022-04-13 18:53:44.611750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55badc63f5fb'
down_revision = '7605e7d9f82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('eisenhower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eisenhower_id'], ['eisenhowers.eisenhower_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    # ### end Alembic commands ###
