"""Einsehowers table creation

Revision ID: 7605e7d9f82d
Revises: a63f6ac7941e
Create Date: 2022-04-13 18:31:00.536187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7605e7d9f82d'
down_revision = 'a63f6ac7941e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eisenhowers',
    sa.Column('eisenhower_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('eisenhower_id'),
    sa.UniqueConstraint('type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eisenhowers')
    # ### end Alembic commands ###
